apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: "auth-srv"
  description: "A microservice that acts as a middleware for authenticating users before giving them access to various StaffingHQ applications"
  annotations:
    github.com/project-slug: Staffing-HQ/auth-srv
    backstage.io/techdocs-ref: dir:.
spec:
  type: openapi
  lifecycle: experimental
  owner: "group:default/developers"
  system: "users-system"
  definition:
    $text: ./openapi.yaml
