apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: auth-srv
  title: Authentication Service
  description: A microservice that acts as a middleware for authenticating users before giving them access to various StaffingHQ applications.
  annotations:
    github.com/project-slug: Staffing-HQ/auth-srv
    backstage.io/techdocs-ref: dir:.
    grafana/overview-dashboard: "http://localhost:3333/d/000000/auth-srv-dashboard"
    grafana/dashboard-selector: "auth-srv"
    backstage.io/kubernetes-id: "auth-srv"
    backstage.io/kubernetes-namespace: default
    backstage.io/kubernetes-label-selector: "app=auth-srv"
spec:
  type: service
  owner: group:default/developers
  lifecycle: experimental
  system: users-system
  providesApis:
    - auth-srv-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: auth-srv-api
  title: Authentication Service API
  description: An API for authentication users.
  annotations:
    github.com/project-slug: Staffing-HQ/auth-srv
    backstage.io/techdocs-ref: dir:.
spec:
  type: openapi
  lifecycle: experimental
  owner: "group:default/developers"
  system: "users-system"
  definition:
    $text: ./openapi.yaml
